### ISSUE TITLE
Enable custom locations on cluster when running connectedk8s 

### ISSUE THREAD

**Issue by dcasati** [Azure/reddog-hybrid-arc#30]
https://docs.microsoft.com/en-us/azure/azure-arc/kubernetes/custom-locations#enable-custom-locations-on-cluster

**Comment by chzbrgr71** [comment]
Hey @dcasati, was this just for Lima or for Arc in general?

**Comment by chzbrgr71** [comment]
I'm going to close this issue until we re-visit Lima down the road
