### ISSUE TITLE
What happened to the script? 

### ISSUE THREAD

**Issue by warrendt** [Azure/reddog-hybrid-arc#41]
Am I missing something, the scripts disappeared in the main branch ?

**Comment by swgriffith** [comment]
Good catch @warrendt
We had a bad merge. I'll fix this morning and update here.

**Comment by warrendt** [comment]
No worries! Thanks man, I am super stoked I found this one, I have a bunch of customers I need to demo this sort of thing for. 
I would like to add some things like the App Services and SQL MI on the clusters, they need to run in data sovereign countries, 
So I would like to modify some of the deployments slightly, but you have done all the hard work! Thank you! 

Also have you been able to implement node selectors at all with GitOps on Clusters that have windows nodes. 
I have a requirement to run windows containers on windows nodes, but onboarded with Arc via Linux system nodes. 

I have been able to get most of it working with rancher. But still playing. 

thanks again
